# Module 2: Data Cleaning and Feature Engineering

## Objective

This notebook cleans the IT Support Ticket dataset by handling missing values, standardizing text fields, removing duplicates, creating new features, and saving the processed dataset for further analysis.

In [1]:
import pandas as pd
import numpy as np
import os
import warnings

warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("../data/IT_Support_Tickets.csv")

In [3]:
df.head()

,Ticket_ID,Created_Date,Resolution_Date,Status,Priority,Ticket_Type,Category,Country,Cluster_ID,Cluster_Name,...,Channel,Description,Tags,Product,Customer_Satisfaction,Escalation_Level,Region,Device_Type,Operating_System,Resolution_Notes
0,TKT000001,2026-05-20,2026-05-23 17:20:00,Open,Critical,Incident,Software,Germany,CL001,Network,...,Portal,User reported an issue.,vpn,Office365,1,L1,APAC,Laptop,Ubuntu,Resolved after troubleshooting.
1,TKT000002,2026-05-02,2026-05-06 09:33:00,Closed,High,Request,Network,India,CL002,Login,...,Chat,User reported an issue.,network,ERP,2,L2,EMEA,Laptop,Windows 11,Resolved after troubleshooting.
2,TKT000003,2025-05-30,2025-05-30 15:56:00,Open,Medium,Request,Email,USA,CL003,Software,...,Chat,User reported an issue.,network,ERP,2,L2,EMEA,Desktop,macOS,Resolved after troubleshooting.
3,TKT000004,2025-08-23,2025-08-25 02:12:00,Closed,High,Problem,Security,Germany,CL001,Software,...,Chat,User reported an issue.,vpn,Office365,2,L3,EMEA,Laptop,Ubuntu,Resolved after troubleshooting.
4,TKT000005,2025-03-26,2025-03-30 09:31:00,Resolved,Critical,Problem,Security,Canada,CL001,Login,...,Phone,User reported an issue.,vpn,ERP,2,L3,NaN,Desktop,Ubuntu,Resolved after troubleshooting.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ticket_ID              10000 non-null  str
 1   Created_Date           10000 non-null  str
 2   Resolution_Date        10000 non-null  str
 3   Status                 10000 non-null  str
 4   Priority               10000 non-null  str
 5   Ticket_Type            10000 non-null  str
 6   Category               10000 non-null  str
 7   Country                10000 non-null  str
 8   Cluster_ID             10000 non-null  str
 9   Cluster_Name           10000 non-null  str
 10  Similarity_Score       10000 non-null  float64
 11  Similarity_Level       10000 non-null  str
 12  First_Response_Date    10000 non-null  str
 13  Assigned_Agent         10000 non-null  str
 14  Team                   10000 non-null  str
 15  SLA_Status             10000 non-null  str
 16  Reopened               10000 non-null  str
 17  Resolution_Code        10000 non-null  str
 18  Department             10000 non-null  str
 19  Customer_ID            10000 non-null  str
 20  Channel                10000 non-null  str
 21  Description            10000 non-null  str
 22  Tags                   10000 non-null  str
 23  Product                10000 non-null  str
 24  Customer_Satisfaction  10000 non-null  int64
 25  Escalation_Level       10000 non-null  str
 26  Region                 6655 non-null   str
 27  Device_Type            10000 non-null  str
 28  Operating_System       10000 non-null  str
 29  Resolution_Notes       10000 non-null  str
dtypes: float64(1), int64(1), str(28)
memory usage: 2.3 MB

In [5]:
df.isnull().sum()

Ticket_ID                   0
Created_Date                0
Resolution_Date             0
Status                      0
Priority                    0
Ticket_Type                 0
Category                    0
Country                     0
Cluster_ID                  0
Cluster_Name                0
Similarity_Score            0
Similarity_Level            0
First_Response_Date         0
Assigned_Agent              0
Team                        0
SLA_Status                  0
Reopened                    0
Resolution_Code             0
Department                  0
Customer_ID                 0
Channel                     0
Description                 0
Tags                        0
Product                     0
Customer_Satisfaction       0
Escalation_Level            0
Region                   3345
Device_Type                 0
Operating_System            0
Resolution_Notes            0
dtype: int64

In [6]:
missing_percentage = (df.isnull().sum()/len(df))*100

missing_df = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": missing_percentage.round(2)
})

missing_df

                       Missing Values  Missing Percentage
Ticket_ID                           0                0.00
Created_Date                        0                0.00
Resolution_Date                     0                0.00
Status                              0                0.00
Priority                            0                0.00
Ticket_Type                         0                0.00
Category                            0                0.00
Country                             0                0.00
Cluster_ID                          0                0.00
Cluster_Name                        0                0.00
Similarity_Score                    0                0.00
Similarity_Level                    0                0.00
First_Response_Date                 0                0.00
Assigned_Agent                      0                0.00
Team                                0                0.00
SLA_Status                          0                0.00
Reopened                            0                0.00
Resolution_Code                     0                0.00
Department                          0                0.00
Customer_ID                         0                0.00
Channel                             0                0.00
Description                         0                0.00
Tags                                0                0.00
Product                             0                0.00
Customer_Satisfaction               0                0.00
Escalation_Level                    0                0.00
Region                           3345               33.45
Device_Type                         0                0.00
Operating_System                    0                0.00
Resolution_Notes                    0                0.00

In [7]:
text_columns = [
    "Description",
    "Tags",
    "Product",
    "Resolution_Notes"
]

for col in text_columns:
    if col in df.columns:
        df[col] = df[col].fillna("Unknown")

In [8]:
df[text_columns].isnull().sum()

Description         0
Tags                0
Product             0
Resolution_Notes    0
dtype: int64

In [9]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [10]:
df.head()

,Ticket_ID,Created_Date,Resolution_Date,Status,Priority,Ticket_Type,Category,Country,Cluster_ID,Cluster_Name,...,Channel,Description,Tags,Product,Customer_Satisfaction,Escalation_Level,Region,Device_Type,Operating_System,Resolution_Notes
0,TKT000001,2026-05-20,2026-05-23 17:20:00,Open,Critical,Incident,Software,Germany,CL001,Network,...,Portal,User reported an issue.,vpn,Office365,1,L1,APAC,Laptop,Ubuntu,Resolved after troubleshooting.
1,TKT000002,2026-05-02,2026-05-06 09:33:00,Closed,High,Request,Network,India,CL002,Login,...,Chat,User reported an issue.,network,ERP,2,L2,EMEA,Laptop,Windows 11,Resolved after troubleshooting.
2,TKT000003,2025-05-30,2025-05-30 15:56:00,Open,Medium,Request,Email,USA,CL003,Software,...,Chat,User reported an issue.,network,ERP,2,L2,EMEA,Desktop,macOS,Resolved after troubleshooting.
3,TKT000004,2025-08-23,2025-08-25 02:12:00,Closed,High,Problem,Security,Germany,CL001,Software,...,Chat,User reported an issue.,vpn,Office365,2,L3,EMEA,Laptop,Ubuntu,Resolved after troubleshooting.
4,TKT000005,2025-03-26,2025-03-30 09:31:00,Resolved,Critical,Problem,Security,Canada,CL001,Login,...,Phone,User reported an issue.,vpn,ERP,2,L3,NaN,Desktop,Ubuntu,Resolved after troubleshooting.

In [11]:
for col in text_columns:
    df[col] = df[col].str.title()

In [12]:
for col in text_columns:
    df[col] = df[col].replace("", "Unknown")

In [13]:
df.head()

,Ticket_ID,Created_Date,Resolution_Date,Status,Priority,Ticket_Type,Category,Country,Cluster_ID,Cluster_Name,...,Channel,Description,Tags,Product,Customer_Satisfaction,Escalation_Level,Region,Device_Type,Operating_System,Resolution_Notes
0,Tkt000001,2026-05-20,2026-05-23 17:20:00,Open,Critical,Incident,Software,Germany,Cl001,Network,...,Portal,User Reported An Issue.,Vpn,Office365,1,L1,Apac,Laptop,Ubuntu,Resolved After Troubleshooting.
1,Tkt000002,2026-05-02,2026-05-06 09:33:00,Closed,High,Request,Network,India,Cl002,Login,...,Chat,User Reported An Issue.,Network,Erp,2,L2,Emea,Laptop,Windows 11,Resolved After Troubleshooting.
2,Tkt000003,2025-05-30,2025-05-30 15:56:00,Open,Medium,Request,Email,Usa,Cl003,Software,...,Chat,User Reported An Issue.,Network,Erp,2,L2,Emea,Desktop,Macos,Resolved After Troubleshooting.
3,Tkt000004,2025-08-23,2025-08-25 02:12:00,Closed,High,Problem,Security,Germany,Cl001,Software,...,Chat,User Reported An Issue.,Vpn,Office365,2,L3,Emea,Laptop,Ubuntu,Resolved After Troubleshooting.
4,Tkt000005,2025-03-26,2025-03-30 09:31:00,Resolved,Critical,Problem,Security,Canada,Cl001,Login,...,Phone,User Reported An Issue.,Vpn,Erp,2,L3,NaN,Desktop,Ubuntu,Resolved After Troubleshooting.

In [14]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [15]:
df = df.drop_duplicates()

In [16]:
print(df.duplicated().sum())

0

In [17]:
print(df["Ticket_ID"].duplicated().sum())

0

In [18]:
df["Created_Date"] = pd.to_datetime(df["Created_Date"])

df["Resolution_Date"] = pd.to_datetime(df["Resolution_Date"])


df["First_Response_Date"] = pd.to_datetime(df["First_Response_Date"])

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ticket_ID              10000 non-null  str
 1   Created_Date           10000 non-null  datetime64[us]
 2   Resolution_Date        10000 non-null  datetime64[us]
 3   Status                 10000 non-null  str
 4   Priority               10000 non-null  str
 5   Ticket_Type            10000 non-null  str
 6   Category               10000 non-null  str
 7   Country                10000 non-null  str
 8   Cluster_ID             10000 non-null  str
 9   Cluster_Name           10000 non-null  str
 10  Similarity_Score       10000 non-null  float64
 11  Similarity_Level       10000 non-null  str
 12  First_Response_Date    10000 non-null  datetime64[us]
 13  Assigned_Agent         10000 non-null  str
 14  Team                   10000 non-null  str
 15  SLA_Status             10000 non-null  str
 16  Reopened               10000 non-null  str
 17  Resolution_Code        10000 non-null  str
 18  Department             10000 non-null  str
 19  Customer_ID            10000 non-null  str
 20  Channel                10000 non-null  str
 21  Description            10000 non-null  str
 22  Tags                   10000 non-null  str
 23  Product                10000 non-null  str
 24  Customer_Satisfaction  10000 non-null  int64
 25  Escalation_Level       10000 non-null  str
 26  Region                 6655 non-null   str
 27  Device_Type            10000 non-null  str
 28  Operating_System       10000 non-null  str
 29  Resolution_Notes       10000 non-null  str
dtypes: datetime64[us](3), float64(1), int64(1), str(25)
memory usage: 2.3 MB

In [20]:
df["Resolution_Duration"] = (
    df["Resolution_Date"] -
    df["Created_Date"]
).dt.total_seconds()/3600

In [21]:
df[
[
"Created_Date",
"Resolution_Date",
"Resolution_Duration"
]
].head()

  Created_Date     Resolution_Date  Resolution_Duration
0   2026-05-20 2026-05-23 17:20:00            89.333333
1   2026-05-02 2026-05-06 09:33:00           105.550000
2   2025-05-30 2025-05-30 15:56:00            15.933333
3   2025-08-23 2025-08-25 02:12:00            50.200000
4   2025-03-26 2025-03-30 09:31:00           105.516667

In [22]:
priority_map = {

"Low":1,

"Medium":2,

"High":3,

"Critical":4

}

df["Priority_Score"] = df["Priority"].map(priority_map)

In [23]:
df[
[
"Priority",
"Priority_Score"
]
].head()

   Priority  Priority_Score
0  Critical               4
1      High               3
2    Medium               2
3      High               3
4  Critical               4

In [24]:
df.describe()

,Created_Date,Resolution_Date,Similarity_Score,First_Response_Date,Customer_Satisfaction,Resolution_Duration,Priority_Score
count,10000,10000,10000.000000,10000,10000.000000,10000.000000,10000.000000
mean,2025-09-28 03:17:51.360000,2025-09-30 16:24:03,0.744618,2025-09-28 04:49:46.680000,2.981800,61.103233,2.511100
min,2025-01-01 00:00:00,2025-01-01 06:26:00,0.500000,2025-01-01 00:13:00,1.000000,1.100000,1.000000
25%,2025-05-18 00:00:00,2025-05-21 00:12:00,0.620000,2025-05-18 01:30:00,2.000000,31.000000,2.000000
50%,2025-09-29 00:00:00,2025-10-01 10:46:30,0.740000,2025-09-29 01:28:00,3.000000,61.075000,3.000000
75%,2026-02-09 00:00:00,2026-02-12 00:04:30,0.870000,2026-02-09 01:12:30,4.000000,91.037500,4.000000
max,2026-06-25 00:00:00,2026-06-29 22:41:00,0.990000,2026-06-25 02:35:00,5.000000,123.000000,4.000000
std,NaN,NaN,0.142872,NaN,1.410414,34.480760,1.123033

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ticket_ID              10000 non-null  str
 1   Created_Date           10000 non-null  datetime64[us]
 2   Resolution_Date        10000 non-null  datetime64[us]
 3   Status                 10000 non-null  str
 4   Priority               10000 non-null  str
 5   Ticket_Type            10000 non-null  str
 6   Category               10000 non-null  str
 7   Country                10000 non-null  str
 8   Cluster_ID             10000 non-null  str
 9   Cluster_Name           10000 non-null  str
 10  Similarity_Score       10000 non-null  float64
 11  Similarity_Level       10000 non-null  str
 12  First_Response_Date    10000 non-null  datetime64[us]
 13  Assigned_Agent         10000 non-null  str
 14  Team                   10000 non-null  str
 15  SLA_Status             10000 non-null  str
 16  Reopened               10000 non-null  str
 17  Resolution_Code        10000 non-null  str
 18  Department             10000 non-null  str
 19  Customer_ID            10000 non-null  str
 20  Channel                10000 non-null  str
 21  Description            10000 non-null  str
 22  Tags                   10000 non-null  str
 23  Product                10000 non-null  str
 24  Customer_Satisfaction  10000 non-null  int64
 25  Escalation_Level       10000 non-null  str
 26  Region                 6655 non-null   str
 27  Device_Type            10000 non-null  str
 28  Operating_System       10000 non-null  str
 29  Resolution_Notes       10000 non-null  str
 30  Resolution_Duration    10000 non-null  float64
 31  Priority_Score         10000 non-null  int64
dtypes: datetime64[us](3), float64(2), int64(2), str(25)
memory usage: 2.4 MB

In [26]:
df.head()

,Ticket_ID,Created_Date,Resolution_Date,Status,Priority,Ticket_Type,Category,Country,Cluster_ID,Cluster_Name,...,Tags,Product,Customer_Satisfaction,Escalation_Level,Region,Device_Type,Operating_System,Resolution_Notes,Resolution_Duration,Priority_Score
0,Tkt000001,2026-05-20,2026-05-23 17:20:00,Open,Critical,Incident,Software,Germany,Cl001,Network,...,Vpn,Office365,1,L1,Apac,Laptop,Ubuntu,Resolved After Troubleshooting.,89.333333,4
1,Tkt000002,2026-05-02,2026-05-06 09:33:00,Closed,High,Request,Network,India,Cl002,Login,...,Network,Erp,2,L2,Emea,Laptop,Windows 11,Resolved After Troubleshooting.,105.550000,3
2,Tkt000003,2025-05-30,2025-05-30 15:56:00,Open,Medium,Request,Email,Usa,Cl003,Software,...,Network,Erp,2,L2,Emea,Desktop,Macos,Resolved After Troubleshooting.,15.933333,2
3,Tkt000004,2025-08-23,2025-08-25 02:12:00,Closed,High,Problem,Security,Germany,Cl001,Software,...,Vpn,Office365,2,L3,Emea,Laptop,Ubuntu,Resolved After Troubleshooting.,50.200000,3
4,Tkt000005,2025-03-26,2025-03-30 09:31:00,Resolved,Critical,Problem,Security,Canada,Cl001,Login,...,Vpn,Erp,2,L3,NaN,Desktop,Ubuntu,Resolved After Troubleshooting.,105.516667,4

In [27]:
os.makedirs("../data/processed",exist_ok=True)

In [28]:
df.to_csv(
"../data/processed/cleaned_IT_Support_Tickets.csv",
index=False
)

print("Dataset saved successfully.")

Dataset saved successfully.

In [29]:
import os

os.listdir("../data/processed")

['cleaned_IT_Support_Tickets.csv']

# Feature Engineering Summary

## Resolution_Duration

Formula:

Resolution_Date − Created_Date

Unit:

Hours

Purpose:

Measures the total time required to resolve a ticket.

Business Value:

Helps evaluate support team performance.

---

## Priority_Score

Mapping

Low = 1

Medium = 2

High = 3

Critical = 4

Purpose

Converts priority into numerical values for analytics and machine learning.