In [ ]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv('/content/customer_support_tickets_200k.csv')

In [5]:
df.head()

,ticket_id,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,region,customer_age,customer_gender,subscription_type,customer_tenure_months,previous_tickets,customer_satisfaction_score,first_response_time_hours,resolution_time_hours,ticket_created_date,ticket_resolved_date,escalated,sla_breached,operating_system,browser,payment_method,language,preferred_contact_time,issue_complexity_score,customer_segment
0,1,Patricia Smith,patricia.smith760@outlook.com,Web Portal,Account Suspension,The payment was deducted from my bank account ...,Data synchronization restored after backend se...,Urgent,Open,Email,North America,31,Male,Free,36,6,5,30.50,108.36,2023-05-17,2023-05-20,No,Yes,MacOS,Edge,PayPal,French,Afternoon,4,Small Business
1,2,Patricia Williams,patricia.williams390@gmail.com,Mobile App,Performance Issue,I found a bug in the latest update affecting r...,Provided step-by-step troubleshooting instruct...,Urgent,Closed,Email,South America,23,Other,Premium,54,20,5,63.81,87.43,2024-01-06,2024-01-19,Yes,Yes,Windows,Firefox,PayPal,English,Afternoon,2,Small Business
2,3,William Anderson,william.anderson651@outlook.com,Web Portal,Performance Issue,The application crashes whenever I try to uplo...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Chat,Europe,47,Female,Premium,60,20,5,16.20,78.50,2022-11-30,2022-12-05,Yes,Yes,Windows,Safari,Bank Transfer,French,Morning,4,Corporate
3,4,David Miller,david.miller672@icloud.com,Payment Gateway,Subscription Cancellation,My subscription was cancelled without my reque...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Social Media,Asia,65,Other,Enterprise,58,18,4,26.38,239.36,2024-03-21,2024-04-04,Yes,No,Windows,Chrome,Credit Card,Spanish,Afternoon,7,Corporate
4,5,Robert Gonzalez,robert.gonzalez391@hotmail.com,Web Portal,Feature Request,The system is not syncing data across devices ...,We have reset the account credentials and advi...,High,Pending Customer,Email,Asia,45,Male,Enterprise,1,8,5,54.98,122.34,2024-08-16,2024-08-24,Yes,No,Linux,NaN,Debit Card,Spanish,Evening,3,Corporate

In [6]:
print(f"Number of Rows    : {df.shape[0]}")
print(f"Number of Columns : {df.shape[1]}")

Number of Rows    : 200000
Number of Columns : 30

In [7]:
print("Columns in the dataset:\n")
print(df.columns.tolist())

Columns in the dataset:

['ticket_id', 'customer_name', 'customer_email', 'product', 'category', 'issue_description', 'resolution_notes', 'priority', 'status', 'channel', 'region', 'customer_age', 'customer_gender', 'subscription_type', 'customer_tenure_months', 'previous_tickets', 'customer_satisfaction_score', 'first_response_time_hours', 'resolution_time_hours', 'ticket_created_date', 'ticket_resolved_date', 'escalated', 'sla_breached', 'operating_system', 'browser', 'payment_method', 'language', 'preferred_contact_time', 'issue_complexity_score', 'customer_segment']

In [8]:
# Display concise information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 30 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ticket_id                    200000 non-null  int64
 1   customer_name                200000 non-null  object
 2   customer_email               200000 non-null  object
 3   product                      200000 non-null  object
 4   category                     200000 non-null  object
 5   issue_description            200000 non-null  object
 6   resolution_notes             200000 non-null  object
 7   priority                     200000 non-null  object
 8   status                       200000 non-null  object
 9   channel                      200000 non-null  object
 10  region                       200000 non-null  object
 11  customer_age                 200000 non-null  int64
 12  customer_gender              200000 non-null  object
 13  subscription_type            200000 non-null  object
 14  customer_tenure_months       200000 non-null  int64
 15  previous_tickets             200000 non-null  int64
 16  customer_satisfaction_score  200000 non-null  int64
 17  first_response_time_hours    200000 non-null  float64
 18  resolution_time_hours        200000 non-null  float64
 19  ticket_created_date          200000 non-null  object
 20  ticket_resolved_date         200000 non-null  object
 21  escalated                    200000 non-null  object
 22  sla_breached                 200000 non-null  object
 23  operating_system             200000 non-null  object
 24  browser                      159977 non-null  object
 25  payment_method               200000 non-null  object
 26  language                     200000 non-null  object
 27  preferred_contact_time       200000 non-null  object
 28  issue_complexity_score       200000 non-null  int64
 29  customer_segment             200000 non-null  object
dtypes: float64(2), int64(6), object(22)
memory usage: 45.8+ MB

In [9]:
# Display data types of all columns
df.dtypes

ticket_id                        int64
customer_name                   object
customer_email                  object
product                         object
category                        object
issue_description               object
resolution_notes                object
priority                        object
status                          object
channel                         object
region                          object
customer_age                     int64
customer_gender                 object
subscription_type               object
customer_tenure_months           int64
previous_tickets                 int64
customer_satisfaction_score      int64
first_response_time_hours      float64
resolution_time_hours          float64
ticket_created_date             object
ticket_resolved_date            object
escalated                       object
sla_breached                    object
operating_system                object
browser                         object
payment_method                  object
language                        object
preferred_contact_time          object
issue_complexity_score           int64
customer_segment                object
dtype: object

In [10]:
# Count missing values in each column
missing_values = df.isnull().sum()

missing_values

ticket_id                          0
customer_name                      0
customer_email                     0
product                            0
category                           0
issue_description                  0
resolution_notes                   0
priority                           0
status                             0
channel                            0
region                             0
customer_age                       0
customer_gender                    0
subscription_type                  0
customer_tenure_months             0
previous_tickets                   0
customer_satisfaction_score        0
first_response_time_hours          0
resolution_time_hours              0
ticket_created_date                0
ticket_resolved_date               0
escalated                          0
sla_breached                       0
operating_system                   0
browser                        40023
payment_method                     0
language                           0
preferred_contact_time             0
issue_complexity_score             0
customer_segment                   0
dtype: int64

In [11]:
missing_percentage = (
    df.isnull().mean() * 100
).round(2)

missing_percentage = missing_percentage.sort_values(ascending=False)

missing_percentage[missing_percentage > 0]

browser    20.01
dtype: float64

In [12]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().mean()*100).round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing Count"] > 0
].sort_values(
    by="Missing Percentage",
    ascending=False
)

missing_summary

         Missing Count  Missing Percentage
browser          40023               20.01

In [13]:
categorical_cols = df.select_dtypes(include='object').columns.tolist()

numerical_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()

print("Categorical Columns:")
print(categorical_cols)

print("\nNumerical Columns:")
print(numerical_cols)

Categorical Columns:
['customer_name', 'customer_email', 'product', 'category', 'issue_description', 'resolution_notes', 'priority', 'status', 'channel', 'region', 'customer_gender', 'subscription_type', 'ticket_created_date', 'ticket_resolved_date', 'escalated', 'sla_breached', 'operating_system', 'browser', 'payment_method', 'language', 'preferred_contact_time', 'customer_segment']

Numerical Columns:
['ticket_id', 'customer_age', 'customer_tenure_months', 'previous_tickets', 'customer_satisfaction_score', 'first_response_time_hours', 'resolution_time_hours', 'issue_complexity_score']

In [14]:
date_columns = [
    'ticket_created_date',
    'ticket_resolved_date'
]

print(df[date_columns].dtypes)

ticket_created_date     object
ticket_resolved_date    object
dtype: object

In [15]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ticket_id,200000.0,100000.500000,57735.171256,1.0,50000.75,100000.50,150000.25,200000.0
customer_age,200000.0,46.469040,16.754304,18.0,32.00,46.00,61.00,75.0
customer_tenure_months,200000.0,30.377675,17.326224,1.0,15.00,30.00,45.00,60.0
previous_tickets,200000.0,9.992115,6.053142,0.0,5.00,10.00,15.00,20.0
customer_satisfaction_score,200000.0,3.001065,1.412273,1.0,2.00,3.00,4.00,5.0
first_response_time_hours,200000.0,36.309180,20.654575,0.5,18.46,36.31,54.22,72.0
resolution_time_hours,200000.0,120.539718,68.969143,1.0,60.81,120.45,180.26,240.0
issue_complexity_score,200000.0,5.501365,2.875587,1.0,3.00,6.00,8.00,10.0

In [16]:
df.describe(include='object').T

,count,unique,top,freq
customer_name,200000,400,Jessica Rodriguez,568
customer_email,200000,191751,barbara.martin919@yahoo.com,4
product,200000,10,Billing System,20111
category,200000,10,Feature Request,20169
issue_description,200000,10,There seems to be a discrepancy in my billing ...,20232
resolution_notes,200000,10,We have reset the account credentials and advi...,20141
priority,200000,4,High,50241
status,200000,5,In Progress,40065
channel,200000,5,Web Form,40090
region,200000,6,Africa,33576
customer_gender,200000,3,Other,66795
subscription_type,200000,4,Free,50147
ticket_created_date,200000,1096,2024-05-11,225
ticket_resolved_date,200000,1110,2024-07-01,229
escalated,200000,2,Yes,100421
sla_breached,200000,2,Yes,100043
operating_system,200000,5,Android,40141
browser,159977,4,Safari,40156
payment_method,200000,5,Crypto,40274
language,200000,6,Japanese,33620
preferred_contact_time,200000,4,Morning,50384
customer_segment,200000,3,Individual,67098

In [19]:
# Ticket distribution by Priority
priority_distribution = (
    df['priority']
    .value_counts()
    .rename_axis('Priority')
    .reset_index(name='Ticket Count')
)

priority_distribution

  Priority  Ticket Count
0     High         50241
1   Urgent         50143
2   Medium         49854
3      Low         49762

In [20]:
priority_distribution['Percentage (%)'] = (
    priority_distribution['Ticket Count']
    / priority_distribution['Ticket Count'].sum()
    * 100
).round(2)

priority_distribution

  Priority  Ticket Count  Percentage (%)
0     High         50241           25.12
1   Urgent         50143           25.07
2   Medium         49854           24.93
3      Low         49762           24.88

In [22]:
# Ticket distribution by Category
category_distribution = (
    df['category']
    .value_counts()
    .rename_axis('Category')
    .reset_index(name='Ticket Count')
)

category_distribution

                    Category  Ticket Count
0            Feature Request         20169
1  Subscription Cancellation         20096
2          Performance Issue         20074
3           Security Concern         20040
4                Login Issue         20002
5            Payment Problem         19997
6                 Bug Report         19981
7             Refund Request         19900
8            Data Sync Issue         19877
9         Account Suspension         19864

In [23]:
category_distribution['Percentage (%)'] = (
    category_distribution['Ticket Count']
    / category_distribution['Ticket Count'].sum()
    * 100
).round(2)

category_distribution

                    Category  Ticket Count  Percentage (%)
0            Feature Request         20169           10.08
1  Subscription Cancellation         20096           10.05
2          Performance Issue         20074           10.04
3           Security Concern         20040           10.02
4                Login Issue         20002           10.00
5            Payment Problem         19997           10.00
6                 Bug Report         19981            9.99
7             Refund Request         19900            9.95
8            Data Sync Issue         19877            9.94
9         Account Suspension         19864            9.93

In [24]:
status_distribution = (
    df['status']
    .value_counts()
    .rename_axis('Status')
    .reset_index(name='Ticket Count')
)

status_distribution['Percentage (%)'] = (
    status_distribution['Ticket Count']
    / status_distribution['Ticket Count'].sum()
    * 100
).round(2)

status_distribution

             Status  Ticket Count  Percentage (%)
0       In Progress         40065           20.03
1            Closed         40029           20.01
2  Pending Customer         40014           20.01
3          Resolved         39970           19.98
4              Open         39922           19.96

In [25]:
channel_distribution = (
    df['channel']
    .value_counts()
    .rename_axis('Channel')
    .reset_index(name='Ticket Count')
)

channel_distribution['Percentage (%)'] = (
    channel_distribution['Ticket Count']
    / channel_distribution['Ticket Count'].sum()
    * 100
).round(2)

channel_distribution

        Channel  Ticket Count  Percentage (%)
0      Web Form         40090           20.04
1         Phone         40073           20.04
2          Chat         40073           20.04
3  Social Media         40038           20.02
4         Email         39726           19.86

In [26]:
print("Priority Distribution")
display(priority_distribution)

print("\nCategory Distribution")
display(category_distribution)

print("\nStatus Distribution")
display(status_distribution)

print("\nChannel Distribution")
display(channel_distribution)

Priority Distribution

  Priority  Ticket Count  Percentage (%)
0     High         50241           25.12
1   Urgent         50143           25.07
2   Medium         49854           24.93
3      Low         49762           24.88

Category Distribution

                    Category  Ticket Count  Percentage (%)
0            Feature Request         20169           10.08
1  Subscription Cancellation         20096           10.05
2          Performance Issue         20074           10.04
3           Security Concern         20040           10.02
4                Login Issue         20002           10.00
5            Payment Problem         19997           10.00
6                 Bug Report         19981            9.99
7             Refund Request         19900            9.95
8            Data Sync Issue         19877            9.94
9         Account Suspension         19864            9.93

Status Distribution

             Status  Ticket Count  Percentage (%)
0       In Progress         40065           20.03
1            Closed         40029           20.01
2  Pending Customer         40014           20.01
3          Resolved         39970           19.98
4              Open         39922           19.96

Channel Distribution

        Channel  Ticket Count  Percentage (%)
0      Web Form         40090           20.04
1         Phone         40073           20.04
2          Chat         40073           20.04
3  Social Media         40038           20.02
4         Email         39726           19.86

In [27]:
text_columns = [
    'customer_name',
    'customer_email',
    'product',
    'category',
    'issue_description',
    'resolution_notes',
    'priority',
    'status',
    'channel',
    'region',
    'customer_gender',
    'subscription_type',
    'operating_system',
    'browser',
    'payment_method',
    'language',
    'preferred_contact_time',
    'customer_segment'
]

df[text_columns].isnull().sum()

customer_name                 0
customer_email                0
product                       0
category                      0
issue_description             0
resolution_notes              0
priority                      0
status                        0
channel                       0
region                        0
customer_gender               0
subscription_type             0
operating_system              0
browser                   40023
payment_method                0
language                      0
preferred_contact_time        0
customer_segment              0
dtype: int64

In [28]:
for col in text_columns:
    print(f"\n{'='*50}")
    print(col)
    print(df[col].head(10))

==================================================
customer_name
0       Patricia Smith
1    Patricia Williams
2     William Anderson
3         David Miller
4      Robert Gonzalez
5         Thomas Smith
6     Michael Martinez
7       Jessica Miller
8     William Anderson
9     Elizabeth Miller
Name: customer_name, dtype: object

==================================================
customer_email
0      patricia.smith760@outlook.com
1     patricia.williams390@gmail.com
2    william.anderson651@outlook.com
3         david.miller672@icloud.com
4     robert.gonzalez391@hotmail.com
5        thomas.smith614@outlook.com
6    michael.martinez409@company.com
7        jessica.miller553@yahoo.com
8      william.anderson256@gmail.com
9      elizabeth.miller992@gmail.com
Name: customer_email, dtype: object

==================================================
product
0              Web Portal
1              Mobile App
2              Web Portal
3         Payment Gateway
4              Web Portal
5    Subscription Service
6    Subscription Service
7              Web Portal
8             API Service
9          Billing System
Name: product, dtype: object

==================================================
category
0           Account Suspension
1            Performance Issue
2            Performance Issue
3    Subscription Cancellation
4              Feature Request
5              Payment Problem
6             Security Concern
7    Subscription Cancellation
8             Security Concern
9            Performance Issue
Name: category, dtype: object

==================================================
issue_description
0    The payment was deducted from my bank account ...
1    I found a bug in the latest update affecting r...
2    The application crashes whenever I try to uplo...
3    My subscription was cancelled without my reque...
4    The system is not syncing data across devices ...
5    There seems to be a discrepancy in my billing ...
6    I would like to request a refund for the recen...
7    Two-factor authentication codes are not being ...
8    The payment was deducted from my bank account ...
9    I am unable to access my account after enterin...
Name: issue_description, dtype: object

==================================================
resolution_notes
0    Data synchronization restored after backend se...
1    Provided step-by-step troubleshooting instruct...
2    Provided step-by-step troubleshooting instruct...
3    Provided step-by-step troubleshooting instruct...
4    We have reset the account credentials and advi...
5    Provided step-by-step troubleshooting instruct...
6    The duplicate charge was reversed and refund p...
7    Subscription status corrected and confirmation...
8    We have reset the account credentials and advi...
9    We have reset the account credentials and advi...
Name: resolution_notes, dtype: object

==================================================
priority
0    Urgent
1    Urgent
2    Medium
3    Medium
4      High
5       Low
6    Medium
7       Low
8       Low
9    Urgent
Name: priority, dtype: object

==================================================
status
0                Open
1              Closed
2              Closed
3              Closed
4    Pending Customer
5         In Progress
6                Open
7            Resolved
8                Open
9              Closed
Name: status, dtype: object

==================================================
channel
0           Email
1           Email
2            Chat
3    Social Media
4           Email
5    Social Media
6           Phone
7           Phone
8            Chat
9    Social Media
Name: channel, dtype: object

==================================================
region
0    North America
1    South America
2           Europe
3             Asia
4             Asia
5    North America
6    North America
7    South America
8           Europe
9           Europe
Name: region, dtype: object

==================================================
customer_gender
0      Male
1     Other
2    Female
3     Other
4      Male
5     Other
6     Other
7    Female
8    Female
9     Other
Name: customer_gender, dtype: object

==================================================
subscription_type
0          Free
1       Premium
2       Premium
3    Enterprise
4    Enterprise
5    Enterprise
6         Basic
7          Free
8    Enterprise
9          Free
Name: subscription_type, dtype: object

==================================================
operating_system
0      MacOS
1    Windows
2    Windows
3    Windows
4      Linux
5    Android
6    Windows
7      MacOS
8        iOS
9    Windows
Name: operating_system, dtype: object

==================================================
browser
0       Edge
1    Firefox
2     Safari
3     Chrome
4        NaN
5        NaN
6     Safari
7    Firefox
8     Safari
9        NaN
Name: browser, dtype: object

==================================================
payment_method
0           PayPal
1           PayPal
2    Bank Transfer
3      Credit Card
4       Debit Card
5           Crypto
6      Credit Card
7           Crypto
8    Bank Transfer
9       Debit Card
Name: payment_method, dtype: object

==================================================
language
0      French
1     English
2      French
3     Spanish
4     Spanish
5      German
6     Chinese
7      German
8    Japanese
9     Chinese
Name: language, dtype: object

==================================================
preferred_contact_time
0    Afternoon
1    Afternoon
2      Morning
3    Afternoon
4      Evening
5    Afternoon
6    Afternoon
7    Afternoon
8        Night
9      Morning
Name: preferred_contact_time, dtype: object

==================================================
customer_segment
0    Small Business
1    Small Business
2         Corporate
3         Corporate
4         Corporate
5         Corporate
6         Corporate
7        Individual
8        Individual
9        Individual
Name: customer_segment, dtype: object

In [29]:
categorical_text = [
    'product',
    'category',
    'priority',
    'status',
    'channel',
    'region',
    'customer_gender',
    'subscription_type',
    'operating_system',
    'browser',
    'payment_method',
    'language',
    'preferred_contact_time',
    'customer_segment'
]

for col in categorical_text:
    print(f"\n{col}")
    print(df[col].unique())

product
['Web Portal' 'Mobile App' 'Payment Gateway' 'Subscription Service'
 'API Service' 'Billing System' 'Cloud Storage' 'E-commerce Store'
 'Analytics Dashboard' 'CRM Platform']

category
['Account Suspension' 'Performance Issue' 'Subscription Cancellation'
 'Feature Request' 'Payment Problem' 'Security Concern' 'Refund Request'
 'Login Issue' 'Bug Report' 'Data Sync Issue']

priority
['Urgent' 'Medium' 'High' 'Low']

status
['Open' 'Closed' 'Pending Customer' 'In Progress' 'Resolved']

channel
['Email' 'Chat' 'Social Media' 'Phone' 'Web Form']

region
['North America' 'South America' 'Europe' 'Asia' 'Africa' 'Australia']

customer_gender
['Male' 'Other' 'Female']

subscription_type
['Free' 'Premium' 'Enterprise' 'Basic']

operating_system
['MacOS' 'Windows' 'Linux' 'Android' 'iOS']

browser
['Edge' 'Firefox' 'Safari' 'Chrome' nan]

payment_method
['PayPal' 'Bank Transfer' 'Credit Card' 'Debit Card' 'Crypto']

language
['French' 'English' 'Spanish' 'German' 'Chinese' 'Japanese']

preferred_contact_time
['Afternoon' 'Morning' 'Evening' 'Night']

customer_segment
['Small Business' 'Corporate' 'Individual']

In [30]:
for col in text_columns:
    blanks = (df[col].astype(str).str.strip() == "").sum()
    print(f"{col}: {blanks}")

customer_name: 0
customer_email: 0
product: 0
category: 0
issue_description: 0
resolution_notes: 0
priority: 0
status: 0
channel: 0
region: 0
customer_gender: 0
subscription_type: 0
operating_system: 0
browser: 0
payment_method: 0
language: 0
preferred_contact_time: 0
customer_segment: 0

In [31]:
for col in ['priority', 'status', 'category']:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

priority
priority
High      50241
Urgent    50143
Medium    49854
Low       49762
Name: count, dtype: int64

status
status
In Progress         40065
Closed              40029
Pending Customer    40014
Resolved            39970
Open                39922
Name: count, dtype: int64

category
category
Feature Request              20169
Subscription Cancellation    20096
Performance Issue            20074
Security Concern             20040
Login Issue                  20002
Payment Problem              19997
Bug Report                   19981
Refund Request               19900
Data Sync Issue              19877
Account Suspension           19864
Name: count, dtype: int64

In [32]:
# Fill missing browser values
df['browser'] = df['browser'].fillna('Unknown')

In [33]:
print(df['browser'].isnull().sum())

0

In [34]:
text_columns = [
    'customer_name',
    'customer_email',
    'product',
    'category',
    'issue_description',
    'resolution_notes',
    'priority',
    'status',
    'channel',
    'region',
    'customer_gender',
    'subscription_type',
    'operating_system',
    'browser',
    'payment_method',
    'language',
    'preferred_contact_time',
    'customer_segment'
]

df[text_columns] = df[text_columns].apply(
    lambda col: col.str.strip() if col.dtype == "object" else col
)

In [35]:
print("Missing Browser Values:", df['browser'].isnull().sum())

print("\nUnique Browser Values:")
print(df['browser'].unique())

Missing Browser Values: 0

Unique Browser Values:
['Edge' 'Firefox' 'Safari' 'Chrome' 'Unknown']

In [36]:
# Convert date columns to datetime format
df['ticket_created_date'] = pd.to_datetime(
    df['ticket_created_date'],
    errors='coerce'
)

df['ticket_resolved_date'] = pd.to_datetime(
    df['ticket_resolved_date'],
    errors='coerce'
)

In [37]:
print(df[['ticket_created_date', 'ticket_resolved_date']].dtypes)

ticket_created_date     datetime64[ns]
ticket_resolved_date    datetime64[ns]
dtype: object

In [38]:
# Create Resolution_Duration in days
df['Resolution_Duration'] = (
    df['ticket_resolved_date'] -
    df['ticket_created_date']
).dt.days

In [39]:
df[['ticket_created_date',
    'ticket_resolved_date',
    'Resolution_Duration']].head()

  ticket_created_date ticket_resolved_date  Resolution_Duration
0          2023-05-17           2023-05-20                    3
1          2024-01-06           2024-01-19                   13
2          2022-11-30           2022-12-05                    5
3          2024-03-21           2024-04-04                   14
4          2024-08-16           2024-08-24                    8

In [40]:
df['Resolution_Duration_Hours'] = (
    df['ticket_resolved_date'] -
    df['ticket_created_date']
).dt.total_seconds() / 3600

In [41]:
priority_mapping = {
    'Low': 1,
    'Medium': 2,
    'High': 3,
    'Urgent': 4
}

df['Priority_Score'] = df['priority'].map(priority_mapping)

In [42]:
df[['priority', 'Priority_Score']].head(10)

  priority  Priority_Score
0   Urgent               4
1   Urgent               4
2   Medium               2
3   Medium               2
4     High               3
5      Low               1
6   Medium               2
7      Low               1
8      Low               1
9   Urgent               4

In [43]:
print(df[['Resolution_Duration', 'Priority_Score']].head())

   Resolution_Duration  Priority_Score
0                    3               4
1                   13               4
2                    5               2
3                   14               2
4                    8               3

In [44]:
print("Missing Resolution_Duration:",
      df['Resolution_Duration'].isnull().sum())

print("Missing Priority_Score:",
      df['Priority_Score'].isnull().sum())

Missing Resolution_Duration: 0
Missing Priority_Score: 0

In [45]:
# Map Category to Ticket Type
type_mapping = {
    'Feature Request': 'Request',
    'Refund Request': 'Request',
    'Subscription Cancellation': 'Request',

    'Login Issue': 'Incident',
    'Account Suspension': 'Incident',
    'Payment Problem': 'Incident',

    'Performance Issue': 'Problem',
    'Bug Report': 'Problem',
    'Data Sync Issue': 'Problem',
    'Security Concern': 'Problem'
}

df['type'] = df['category'].map(type_mapping)

In [46]:
df[['category', 'type']].head(15)

                     category      type
0          Account Suspension  Incident
1           Performance Issue   Problem
2           Performance Issue   Problem
3   Subscription Cancellation   Request
4             Feature Request   Request
5             Payment Problem  Incident
6            Security Concern   Problem
7   Subscription Cancellation   Request
8            Security Concern   Problem
9           Performance Issue   Problem
10            Feature Request   Request
11           Security Concern   Problem
12         Account Suspension  Incident
13         Account Suspension  Incident
14            Feature Request   Request

In [47]:
type_distribution = (
    df['type']
      .value_counts()
      .rename_axis('Type')
      .reset_index(name='Ticket Count')
)

type_distribution['Percentage (%)'] = (
    type_distribution['Ticket Count']
    / len(df)
    * 100
).round(2)

type_distribution

       Type  Ticket Count  Percentage (%)
0   Problem         79972           39.99
1   Request         60165           30.08
2  Incident         59863           29.93

In [48]:
# Save the processed dataset
df.to_csv('customer_support_tickets_processed.csv', index=False)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!