In [ ]:
# Core libraries for data acquisition, profiling, and feature engineering
import pandas as pd
import numpy as np

In [ ]:
df = pd.set_option("display.max_columns", None)
df = pd.set_option("display.width", 150)
df = pd.read_csv("customer_sp_ticket.csv")
#  Define the saving path variable
CLEANED_FILE = "customer_support_tickets.csv"

In [ ]:
print("First 5 Records")
df.head()

First 5 Records

,ticket_id,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,region,customer_age,customer_gender,subscription_type,customer_tenure_months,previous_tickets,customer_satisfaction_score,first_response_time_hours,resolution_time_hours,ticket_created_date,ticket_resolved_date,escalated,sla_breached,operating_system,browser,payment_method,language,preferred_contact_time,issue_complexity_score,customer_segment
0,1,Patricia Smith,patricia.smith760@outlook.com,Web Portal,Account Suspension,The payment was deducted from my bank account ...,Data synchronization restored after backend se...,Urgent,Open,Email,North America,31.0,Male,Free,36.0,6.0,5.0,30.50,108.36,2023-05-17,2023-05-20,No,Yes,MacOS,Edge,PayPal,French,Afternoon,4.0,Small Business
1,2,Patricia Williams,patricia.williams390@gmail.com,Mobile App,Performance Issue,I found a bug in the latest update affecting r...,Provided step-by-step troubleshooting instruct...,Urgent,Closed,Email,South America,23.0,Other,Premium,54.0,20.0,5.0,63.81,87.43,2024-01-06,2024-01-19,Yes,Yes,Windows,Firefox,PayPal,English,Afternoon,2.0,Small Business
2,3,William Anderson,william.anderson651@outlook.com,Web Portal,Performance Issue,The application crashes whenever I try to uplo...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Chat,Europe,47.0,Female,Premium,60.0,20.0,5.0,16.20,78.50,2022-11-30,2022-12-05,Yes,Yes,Windows,Safari,Bank Transfer,French,Morning,4.0,Corporate
3,4,David Miller,david.miller672@icloud.com,Payment Gateway,Subscription Cancellation,My subscription was cancelled without my reque...,Provided step-by-step troubleshooting instruct...,Medium,Closed,Social Media,Asia,65.0,Other,Enterprise,58.0,18.0,4.0,26.38,239.36,2024-03-21,2024-04-04,Yes,No,Windows,Chrome,Credit Card,Spanish,Afternoon,7.0,Corporate
4,5,Robert Gonzalez,robert.gonzalez391@hotmail.com,Web Portal,Feature Request,The system is not syncing data across devices ...,We have reset the account credentials and advi...,High,Pending Customer,Email,Asia,45.0,Male,Enterprise,1.0,8.0,5.0,54.98,122.34,2024-08-16,2024-08-24,Yes,No,Linux,NaN,Debit Card,Spanish,Evening,3.0,Corporate

In [ ]:
print("Last 5 Records")
df.tail()

Last 5 Records

,ticket_id,customer_name,customer_email,product,category,issue_description,resolution_notes,priority,status,channel,region,customer_age,customer_gender,subscription_type,customer_tenure_months,previous_tickets,customer_satisfaction_score,first_response_time_hours,resolution_time_hours,ticket_created_date,ticket_resolved_date,escalated,sla_breached,operating_system,browser,payment_method,language,preferred_contact_time,issue_complexity_score,customer_segment
31300,31301,Elizabeth Smith,elizabeth.smith684@yahoo.com,Subscription Service,Security Concern,I found a bug in the latest update affecting r...,Data synchronization restored after backend se...,Medium,In Progress,Phone,Europe,41.0,Other,Enterprise,48.0,18.0,4.0,30.20,43.56,2022-07-21,2022-07-27,No,No,Windows,Safari,Bank Transfer,Spanish,Evening,10.0,Individual
31301,31302,Barbara Gonzalez,barbara.gonzalez906@company.com,Web Portal,Account Suspension,My subscription was cancelled without my reque...,Payment gateway timeout issue fixed and monito...,High,Closed,Phone,North America,74.0,Male,Premium,38.0,0.0,2.0,29.92,180.92,2024-03-13,2024-03-26,Yes,No,MacOS,Safari,Credit Card,French,Afternoon,7.0,Individual
31302,31303,David Rodriguez,david.rodriguez813@icloud.com,Billing System,Bug Report,I would like to request a refund for the recen...,We have reset the account credentials and advi...,Urgent,In Progress,Email,South America,65.0,Other,Premium,26.0,14.0,5.0,33.70,232.44,2024-08-21,2024-08-30,Yes,No,Linux,Firefox,Bank Transfer,German,Evening,2.0,Small Business
31303,31304,Jessica Williams,jessica.williams615@company.com,E-commerce Store,Payment Problem,I would like to request a refund for the recen...,Payment gateway timeout issue fixed and monito...,Urgent,Open,Web Form,South America,58.0,Female,Free,38.0,18.0,4.0,6.26,146.44,2023-06-28,2023-06-30,No,No,Android,Edge,Debit Card,Chinese,Night,9.0,Corporate
31304,31305,Michael Smith,michael.smith690@company.com,Analyt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print("Dataset Shape:")
print(df.shape)

Dataset Shape:
(31305, 30)

In [ ]:
df.columns

Index(['ticket_id', 'customer_name', 'customer_email', 'product', 'category', 'issue_description', 'resolution_notes', 'priority', 'status',
       'channel', 'region', 'customer_age', 'customer_gender', 'subscription_type', 'customer_tenure_months', 'previous_tickets',
       'customer_satisfaction_score', 'first_response_time_hours', 'resolution_time_hours', 'ticket_created_date', 'ticket_resolved_date',
       'escalated', 'sla_breached', 'operating_system', 'browser', 'payment_method', 'language', 'preferred_contact_time', 'issue_complexity_score',
       'customer_segment'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31305 entries, 0 to 31304
Data columns (total 30 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ticket_id                    31305 non-null  int64
 1   customer_name                31305 non-null  object
 2   customer_email               31305 non-null  object
 3   product                      31305 non-null  object
 4   category                     31304 non-null  object
 5   issue_description            31304 non-null  object
 6   resolution_notes             31304 non-null  object
 7   priority                     31304 non-null  object
 8   status                       31304 non-null  object
 9   channel                      31304 non-null  object
 10  region                       31304 non-null  object
 11  customer_age                 31304 non-null  float64
 12  customer_gender              31304 non-null  object
 13  subscription_type            31304 non-null  object
 14  customer_tenure_months       31304 non-null  float64
 15  previous_tickets             31304 non-null  float64
 16  customer_satisfaction_score  31304 non-null  float64
 17  first_response_time_hours    31304 non-null  float64
 18  resolution_time_hours        31304 non-null  float64
 19  ticket_created_date          31304 non-null  object
 20  ticket_resolved_date         31304 non-null  object
 21  escalated                    31304 non-null  object
 22  sla_breached                 31304 non-null  object
 23  operating_system             31304 non-null  object
 24  browser                      25062 non-null  object
 25  payment_method               31304 non-null  object
 26  language                     31304 non-null  object
 27  preferred_contact_time       31304 non-null  object
 28  issue_complexity_score       31304 non-null  float64
 29  customer_segment             31304 non-null  object
dtypes: float64(7), int64(1), object(22)
memory usage: 7.2+ MB

In [ ]:
df.dtypes

ticket_id                        int64
customer_name                   object
customer_email                  object
product                         object
category                        object
issue_description               object
resolution_notes                object
priority                        object
status                          object
channel                         object
region                          object
customer_age                   float64
customer_gender                 object
subscription_type               object
customer_tenure_months         float64
previous_tickets               float64
customer_satisfaction_score    float64
first_response_time_hours      float64
resolution_time_hours          float64
ticket_created_date             object
ticket_resolved_date            object
escalated                       object
sla_breached                    object
operating_system                object
browser                         object
payment_method                  object
language                        object
preferred_contact_time          object
issue_complexity_score         float64
customer_segment                object
dtype: object

In [ ]:
schema_summary = pd.DataFrame({
    "Column": df.columns,
    "Dtype": df.dtypes.astype(str).values,
    "Non-Null Count": df.notnull().sum().values,
    "Unique Values": [df[col].nunique() for col in df.columns]
})
schema_summary

                         Column    Dtype  Non-Null Count  Unique Values
0                     ticket_id    int64           31305          31305
1                 customer_name   object           31305            400
2                customer_email   object           31305          31111
3                       product   object           31305             11
4                      category   object           31304             10
5             issue_description   object           31304             10
6              resolution_notes   object           31304             10
7                      priority   object           31304              4
8                        status   object           31304              5
9                       channel   object           31304              5
10                       region   object           31304              6
11                 customer_age  float64           31304             58
12              customer_gender   object           31304              3
13            subscription_type   object           31304              4
14       customer_tenure_months  float64           31304             60
15             previous_tickets  float64           31304             21
16  customer_satisfaction_score  float64           31304              5
17    first_response_time_hours  float64           31304           7069
18        resolution_time_hours  float64           31304          17451
19          ticket_created_date   object           31304           1096
20         ticket_resolved_date   object           31304           1109
21                    escalated   object           31304              2
22                 sla_breached   object           31304              2
23             operating_system   object           31304              5
24                      browser   object           25062              4
25               payment_method   object           31304              5
26                     language   object           31304              6
27       preferred_contact_time   object           31304              4
28       issue_complexity_score  float64           31304             10
29             customer_segment   object           31304              3

In [ ]:
df.describe()

,ticket_id,customer_age,customer_tenure_months,previous_tickets,customer_satisfaction_score,first_response_time_hours,resolution_time_hours,issue_complexity_score
count,31305.000000,31304.000000,31304.000000,31304.000000,31304.000000,31304.000000,31304.000000,31304.000000
mean,15653.000000,46.438027,30.354939,9.987733,2.994953,36.338559,120.514283,5.508082
std,9037.119425,16.697718,17.417383,6.056125,1.410631,20.774838,68.823305,2.875384
min,1.000000,18.000000,1.000000,0.000000,1.000000,0.500000,1.010000,1.000000
25%,7827.000000,32.000000,15.000000,5.000000,2.000000,18.340000,61.210000,3.000000
50%,15653.000000,46.000000,30.000000,10.000000,3.000000,36.375000,120.480000,6.000000
75%,23479.000000,61.000000,46.000000,15.000000,4.000000,54.412500,179.830000,8.000000
max,31305.000000,75.000000,60.000000,20.000000,5.000000,72.000000,239.980000,10.000000

In [ ]:
df.isnull().sum()

ticket_id                         0
customer_name                     0
customer_email                    0
product                           0
category                          1
issue_description                 1
resolution_notes                  1
priority                          1
status                            1
channel                           1
region                            1
customer_age                      1
customer_gender                   1
subscription_type                 1
customer_tenure_months            1
previous_tickets                  1
customer_satisfaction_score       1
first_response_time_hours         1
resolution_time_hours             1
ticket_created_date               1
ticket_resolved_date              1
escalated                         1
sla_breached                      1
operating_system                  1
browser                        6243
payment_method                    1
language                          1
preferred_contact_time            1
issue_complexity_score            1
customer_segment                  1
dtype: int64

In [ ]:
df['category'].value_counts()

category
Feature Request              3203
Subscription Cancellation    3181
Security Concern             3165
Login Issue                  3132
Refund Request               3121
Performance Issue            3108
Account Suspension           3107
Bug Report                   3103
Data Sync Issue              3103
Payment Problem              3081
Name: count, dtype: int64

In [ ]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing %": (df.isnull().sum() / len(df) * 100).round(2)
}).sort_values("Missing Count", ascending=False)

missing_summary[missing_summary["Missing Count"] > 0]

                             Missing Count  Missing %
browser                               6243      19.94
category                                 1       0.00
channel                                  1       0.00
status                                   1       0.00
priority                                 1       0.00
issue_description                        1       0.00
region                                   1       0.00
customer_age                             1       0.00
customer_gender                          1       0.00
subscription_type                        1       0.00
previous_tickets                         1       0.00
customer_satisfaction_score              1       0.00
customer_tenure_months                   1       0.00
resolution_notes                         1       0.00
escalated                                1       0.00
sla_breached                             1       0.00
operating_system                         1       0.00
payment_method                           1       0.00
resolution_time_hours                    1       0.00
ticket_created_date                      1       0.00
ticket_resolved_date                     1       0.00
first_response_time_hours                1       0.00
language                                 1       0.00
preferred_contact_time                   1       0.00
issue_complexity_score                   1       0.00
customer_segment                         1       0.00

In [ ]:
type_map = {
    "Feature Request": "Request",
    "Subscription Cancellation": "Request",
    "Refund Request": "Request",
    "Account Suspension": "Request",
    "Performance Issue": "Problem",
    "Bug Report": "Problem",
    "Login Issue": "Incident",
    "Security Concern": "Incident",
    "Payment Problem": "Incident",
    "Data Sync Issue": "Incident",
}

df["Type"] = df["category"].map(type_map)

# Sanity check — confirm every category mapped, no nulls introduced
assert df["Type"].isnull().sum() == 0, "Unmapped category found — update type_map"

df[["category", "Type"]].drop_duplicates().sort_values("Type")

AssertionError: Unmapped category found — update type_map

In [ ]:
type_dist = df["Type"].value_counts()
type_pct = (df["Type"].value_counts(normalize=True) * 100).round(2)
pd.DataFrame({"Ticket Count": type_dist, "Share (%)": type_pct})

In [ ]:
# --- Initial Ticket Distribution by Priority ---
priority_dist = df["priority"].value_counts()
priority_pct = (df["priority"].value_counts(normalize=True) * 100).round(2)
pd.DataFrame({"Ticket Count": priority_dist, "Share (%)": priority_pct})

In [ ]:
# --- Initial Ticket Distribution by Category ---
category_dist = df["category"].value_counts()
category_pct = (df["category"].value_counts(normalize=True) * 100).round(2)
pd.DataFrame({"Ticket Count": category_dist, "Share (%)": category_pct})

In [ ]:
# --- Combined view: Type x Priority cross-tab ---
pd.crosstab(df["Type"], df["priority"])

In [ ]:
df["ticket_created_date"] = pd.to_datetime(df["ticket_created_date"], errors="coerce")
df["ticket_resolved_date"] = pd.to_datetime(df["ticket_resolved_date"], errors="coerce")

date_parse_failures = df["ticket_created_date"].isna().sum() + df["ticket_resolved_date"].isna().sum()
print(f"Date parsing failures: {date_parse_failures}")

In [ ]:
df["Resolution_Duration_Days"] = (
    df["ticket_resolved_date"] - df["ticket_created_date"]
).dt.days

df["Resolution_Duration_Days"].describe()

In [ ]:
day_counts = df["Resolution_Duration_Days"].value_counts().sort_index()
print(day_counts)

In [ ]:
pd.crosstab(df["operating_system"], df["browser"])

In [ ]:
browser_mode = df["browser"].mode()[0]
df["browser"] = df["browser"].fillna(browser_mode)
print(f"Mode browser value used for imputation: '{browser_mode}'")

In [ ]:
df["browser"].isnull().sum()

In [ ]:
priority_map = {"Low": 1, "Medium": 2, "High": 3, "Urgent": 4}
df["Priority_Score"] = df["priority"].map(priority_map)

df[["priority", "Priority_Score"]].drop_duplicates().sort_values("Priority_Score")

In [ ]:
inconsistent = df[df["Resolution_Duration_Days"] < 0]
print(f"Records with resolved date earlier than created date: {len(inconsistent):,} "
      f"({len(inconsistent) / len(df) * 100:.2f}% of dataset)")
inconsistent[["ticket_id", "ticket_created_date", "ticket_resolved_date", "status"]].head(10)

In [ ]:
print("Post-cleaning shape:", df.shape)
print()
print("Missing values remaining:")
print(df.isnull().sum()[df.isnull().sum() > 0])

In [ ]:
df.head()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
plt.figure(figsize=(10,5))

sns.countplot(data=df, x='category')

plt.xticks(rotation=45)

plt.title("Ticket Category Distribution")

plt.show()

In [ ]:
plt.figure(figsize=(6,4))

sns.countplot(data=df, x='priority')

plt.title("Ticket Priority Distribution")

plt.show()

In [ ]:
plt.figure(figsize=(6,4))

sns.countplot(data=df, x='status')

plt.title("Ticket Status Distribution")

plt.show()

In [ ]:
df.to_csv(CLEANED_FILE, index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!